#var
#FLAGS = -Wall -Werror -Wextra -pedantic -g 

#default
all: printf

main:
	gcc $(FLAGS) shellHeader.h memoryFunc.c stringFunc.c customFunc.c main.c
alloc:
	gcc -g shellHeader.h memoryFunc.c stringFunc.c customFunc.c test.c
printf:
	gcc -g shellHeader.h memoryFunc.c stringFunc.c customFunc.c printFunc.c test.c
